ingress-nginx:
  controller:
    watchIngressWithoutClass: true
    terminationGracePeriodSeconds: 0
    publishService:
      enabled: false
    extraArgs:
      publish-status-address: localhost
    service:
      type: NodePort
